// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

static const int numThreads = 8;


RWStructuredBuffer<float4> points;

int numOfPointsPerAxis;
int chunkSize;
float3 centre;
float spacing;
int worldSize;
float3 offset;



int indexFromCoord(uint x, uint y, uint z)
{
    
    return z * numOfPointsPerAxis * numOfPointsPerAxis + y * numOfPointsPerAxis + x;
}
